on:
  push:
    paths:
      - 'example/**'
      - 'src/**'
jobs:
  src:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.2
        with:
          dfx-version: 0.8.1
          install-moc: true
          vessel-version: 0.6.2
      - run: |
          cd example
          moc $(vessel sources) --check src/example/main.mo
