on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.8.4
          vessel-version: 0.6.2
      - run: for i in test/*.mo ; do $(vessel bin)/moc $(vessel sources) -r $i ; done
